version: '3.8'

services:

  nginx:
    image: nginx:1.21
    ports:
      - 80:80
    volumes:
      - ./src:/usr/src/blog
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - rust

  rust:
    build: .

  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgres

volumes:
  registry:
    driver: local
  db:
